name: CI

on: [push]

jobs:
  build:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v1
    - name: Crea imagen en Docker
      run: docker build . -t lab-final:1.0
    - name: Imagen Creada...1....2
      run: echo imagen creada
    - name: Realiza install
      run: npm install
    - name: Realiza test
      run: npm test
    - name: push docker hub
      run: docker push ramiro1903176/lab-final:1.0
    - name: Deploy cluster k3d
      run: kubectl apply -f .\deployment.yaml