name: CI

on: [push]

jobs:
  build:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v1
    - name: Crea imagen en Docker
      run: docker build . -t lab-final:1.0
    - name: Imagen Creada...1....
    - name: npm install
      run: npm install
    - name: npm test
      run: npm test
    - name: Echo ........
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.